log = log/hw4_$(tgz).log
error = error/hw4_$(tgz).log
output = output/hw4_$(tgz).out

container_image = osdf:///ospool/uc-shared/public/OSG-Staff/xalim_stat/R_tidyverse_FITSio.sif

executable = hw4.sh
arguments = $(tgz)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT

transfer_input_files = hw4.R, /home/groups/STAT_DSCP/boss/tgz/$(tgz), /home/groups/STAT_DSCP/boss/cB58_Lyman_break.fit

request_cpus = 1
request_memory = 1300MB
request_disk = 1300MB

queue tgz from tgz_all.txt

